train:
  model_name: evaluation_path_balanced_uni2h
  main_output: 'outputs' 
  model_type: 'MahmoodLab/UNI2-h' #'MahmoodLab/UNI2-h', 'MahmoodLab/UNI','prov-gigapath/prov-gigapath'
  batch_size_per_gpu: 64
  seed: 0
  num_workers: 10
  epochs: 10
  num_classes: 9 
  use_pretrained: True
  cache_dataset: true   
  visualize: False
  vit_ckpt_path: "outputs/path_balanced/teacher_checkpoints/iter_60000"  #  "outputs/training_test_3/teacher_checkpoints/iter_120" 
dataset:  
  dataset_path: /media/mgokmen/e487345b-cde7-487b-9198-bfb8d41ce994/450-balanced-cases
  shuffle: true
  resize: True
  mean:
    - 0.7405159
    - 0.5329508
    - 0.70579445
  std:
    - 0.1651425
    - 0.21736613
    - 0.15739934

#Dataset Mean: [0.3384491 0.3384491 0.3384491]
#Dataset Std: [0.16263764 0.16263764 0.16263764]
